"""Versioned schema migrations — the same house style as HESTIA and the Hub.

A ``schema_migrations`` bookkeeping table, a list of numbered revisions, fail-loud apply. The
production contract is the revision list: product tables are never created with
``IF NOT EXISTS`` at startup, because that silently accepts a table somebody else shaped.

Rules for adding a revision:

* never edit a revision that has shipped — a database that already applied it will not run it
  again, so an edit only reaches fresh installs and the two drift apart;
* a statement is either one string for every backend, or a dict keyed by ``backend_type``
  when the engines genuinely disagree (identity columns are the usual case);
* ``tests/test_migrations.py`` applies the whole list to SQLite, and to Postgres when
  ``HISTOR_TEST_DATABASE_URL`` is set, then checks the column contract below.

Run by hand: ``python -m histor.migrations up|status``. ``histor serve`` applies pending
revisions before it listens and refuses to start on a half-migrated database.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime

from histor.db import Backend, Tx

Statements = tuple[str, ...] | dict[str, tuple[str, ...]]

_IDENTITY = {
    "sqlite": "INTEGER PRIMARY KEY",
    "postgresql": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
}

_COMMON_001: tuple[str, ...] = (
    """
    CREATE TABLE meta (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    )
    """,
    # One row per (registry name, endpoint). A server with two remotes is two subjects:
    # the endpoint is inside the MTL descriptor, so it is inside the digest.
    """
    CREATE TABLE targets (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        endpoint TEXT NOT NULL,
        transport TEXT NOT NULL,
        registry TEXT NOT NULL,
        title TEXT,
        description TEXT,
        version TEXT,
        repository TEXT,
        website TEXT,
        first_listed TEXT NOT NULL,
        last_listed TEXT NOT NULL,
        delisted INTEGER NOT NULL DEFAULT 0,
        skip_reason TEXT,
        last_attempt TEXT,
        last_status TEXT,
        last_detail TEXT,
        last_ok TEXT,
        current_subject TEXT,
        current_toolset TEXT,
        current_count INTEGER,
        first_pinned TEXT,
        unchanged_since TEXT,
        observations INTEGER NOT NULL DEFAULT 0,
        ok_observations INTEGER NOT NULL DEFAULT 0,
        changes INTEGER NOT NULL DEFAULT 0,
        block_matches INTEGER,
        advise_matches INTEGER,
        record_matches INTEGER,
        chain_label TEXT,
        last_continuity_at TEXT,
        failure_reported INTEGER NOT NULL DEFAULT 0
    )
    """,
    "CREATE INDEX targets_name ON targets(name)",
    "CREATE INDEX targets_endpoint ON targets(endpoint)",
    # Content-addressed JSON: tool sets, descriptors, pattern sets, record sets. Keyed by the
    # SRI digest the labels cite, so a label's evidence is retrievable by the value it carries.
    """
    CREATE TABLE blobs (
        digest TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        body TEXT NOT NULL
    )
    """,
    # The log. leaf_index is the label's position in the Merkle tree and is never reused.
    """
    CREATE TABLE labels (
        id TEXT PRIMARY KEY,
        target_id TEXT,
        method TEXT NOT NULL,
        verdict TEXT NOT NULL,
        subject TEXT NOT NULL,
        observed_at TEXT NOT NULL,
        issued_at TEXT NOT NULL,
        digest TEXT NOT NULL UNIQUE,
        leaf_index BIGINT NOT NULL UNIQUE,
        body TEXT NOT NULL
    )
    """,
    "CREATE INDEX labels_target ON labels(target_id, leaf_index)",
    """
    CREATE TABLE scans (
        toolset TEXT NOT NULL,
        pattern_set TEXT NOT NULL,
        matches TEXT NOT NULL,
        PRIMARY KEY (toolset, pattern_set)
    )
    """,
    # Complete Merkle subtrees only (see histor.merkle). Hashes are lowercase hex so both
    # engines store and compare them the same way.
    """
    CREATE TABLE log_nodes (
        level INTEGER NOT NULL,
        idx BIGINT NOT NULL,
        hash TEXT NOT NULL,
        PRIMARY KEY (level, idx)
    )
    """,
    """
    CREATE TABLE sths (
        tree_size BIGINT PRIMARY KEY,
        root TEXT NOT NULL,
        timestamp TEXT NOT NULL,
        body TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE client_reports (
        target_id TEXT NOT NULL,
        toolset TEXT NOT NULL,
        day TEXT NOT NULL,
        count INTEGER NOT NULL,
        PRIMARY KEY (target_id, toolset, day)
    )
    """,
)

# Tables with a generated key: the one place the engines disagree on DDL.
_SERIAL_001: tuple[str, ...] = (
    """
    CREATE TABLE runs (
        id {IDENTITY},
        started_at TEXT NOT NULL,
        finished_at TEXT,
        stats TEXT
    )
    """,
    """
    CREATE TABLE observations (
        id {IDENTITY},
        target_id TEXT NOT NULL,
        run_id BIGINT,
        observed_at TEXT NOT NULL,
        status TEXT NOT NULL,
        detail TEXT,
        subject TEXT,
        toolset TEXT,
        tool_count INTEGER,
        pages INTEGER,
        protocol TEXT,
        server_name TEXT,
        server_version TEXT
    )
    """,
    """
    CREATE TABLE changes (
        id {IDENTITY},
        target_id TEXT NOT NULL,
        observed_at TEXT NOT NULL,
        from_subject TEXT,
        to_subject TEXT,
        from_toolset TEXT,
        to_toolset TEXT,
        summary TEXT NOT NULL,
        label_id TEXT
    )
    """,
)

_INDEXES_001: tuple[str, ...] = (
    "CREATE INDEX observations_target ON observations(target_id, observed_at)",
    "CREATE INDEX observations_toolset ON observations(target_id, toolset)",
    "CREATE INDEX changes_time ON changes(observed_at)",
    "CREATE INDEX changes_target ON changes(target_id, observed_at)",
)

MIGRATION_001: dict[str, tuple[str, ...]] = {
    backend: _COMMON_001 + tuple(t.replace("{IDENTITY}", ddl) for t in _SERIAL_001) + _INDEXES_001
    for backend, ddl in _IDENTITY.items()
}

# Which WARDEN pattern set and record set each target's scan labels were issued under, as
# "<pattern-set digest>|<record-set digest>". A single global "the sets changed, rescan all" flag
# could not survive an interrupted crawl: either the targets it never reached kept labels under
# the old set, or a retry re-issued labels for the ones it had (audit F19). Backfilled from the
# sets the last completed crawl recorded, so upgrading re-issues nothing.
MIGRATION_002: tuple[str, ...] = (
    "ALTER TABLE targets ADD COLUMN scan_sets TEXT",
    """
    UPDATE targets SET scan_sets =
        (SELECT value FROM meta WHERE key = 'pattern_set') || '|' || (SELECT value FROM meta WHERE key = 'record_set')
    WHERE current_toolset IS NOT NULL
    """,
    # /stats sums client reports over a window of days on every call.
    "CREATE INDEX client_reports_day ON client_reports(day)",
)

# (version, name, statements)
MIGRATIONS: list[tuple[int, str, Statements]] = [
    (1, "001_initial", MIGRATION_001),
    (2, "002_scan_sets", MIGRATION_002),
]

# The column contract for the table every page reads. A revision that changes it updates
# this tuple in the same change, or the startup check refuses the database.
TARGET_COLUMNS: tuple[str, ...] = (
    "id", "name", "endpoint", "transport", "registry", "title", "description", "version",
    "repository", "website", "first_listed", "last_listed", "delisted", "skip_reason",
    "last_attempt", "last_status", "last_detail", "last_ok", "current_subject",
    "current_toolset", "current_count", "first_pinned", "unchanged_since", "observations",
    "ok_observations", "changes", "block_matches", "advise_matches", "record_matches",
    "chain_label", "last_continuity_at", "failure_reported", "scan_sets",
)


class MigrationError(RuntimeError):
    """Schema apply failed. Do not serve a half-migrated log."""


def statements_for(statements: Statements, backend_type: str) -> tuple[str, ...]:
    if isinstance(statements, dict):
        return statements.get(backend_type, ())
    return statements


def _now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ensure_bookkeeping(tx: Tx) -> None:
    tx.execute(
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        "version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL)"
    )


def applied_versions(backend: Backend) -> set[int]:
    with backend.read() as tx:
        rows = tx.execute("SELECT version FROM schema_migrations")
    return {int(r["version"]) for r in rows}


def current_version(backend: Backend) -> int:
    versions = applied_versions(backend)
    return max(versions) if versions else 0


def target_columns(backend: Backend) -> tuple[str, ...]:
    with backend.read() as tx:
        if tx.backend_type == "sqlite":
            rows = tx.execute("PRAGMA table_info(targets)")
            return tuple(str(r["name"]) for r in rows)
        rows = tx.execute(
            "SELECT column_name AS name FROM information_schema.columns "
            "WHERE table_schema = current_schema() AND table_name = 'targets' ORDER BY ordinal_position"
        )
        return tuple(str(r["name"]) for r in rows)


def apply_migrations(backend: Backend) -> int:
    """Apply pending revisions, each in its own transaction. Returns the head version."""
    try:
        with backend.transaction() as tx:
            _ensure_bookkeeping(tx)
        applied = applied_versions(backend)
        head = 0
        for version, name, statements in MIGRATIONS:
            head = version
            if version in applied:
                continue
            try:
                with backend.transaction() as tx:
                    for statement in statements_for(statements, backend.backend_type):
                        tx.execute(statement.strip())
                    tx.execute(
                        "INSERT INTO schema_migrations (version, name, applied_at) VALUES (?, ?, ?)",
                        (version, name, _now()),
                    )
            except Exception as exc:
                raise MigrationError(f"migration {name} failed: {exc}") from exc
        known = {v for v, _, _ in MIGRATIONS}
        unknown = applied_versions(backend) - known
        if unknown:
            # A database a newer HISTOR migrated. Serving it with older code would read columns
            # this build does not know how to keep consistent.
            raise MigrationError(f"database is at revisions {sorted(unknown)} this build does not know")
        cols = target_columns(backend)
        if cols != TARGET_COLUMNS:
            raise MigrationError(f"targets columns {cols} do not match the contract {TARGET_COLUMNS}")
        return head
    except MigrationError:
        raise
    except Exception as exc:
        raise MigrationError(f"migrate failed: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    from histor.config import load_settings
    from histor.db import open_backend

    args = list(sys.argv[1:] if argv is None else argv)
    settings = load_settings()
    backend = open_backend(settings.db_path, settings.database_url)
    try:
        if not args or args[0] in {"up", "apply"}:
            version = apply_migrations(backend)
            print(f"backend={backend.backend_type} version={version}")
            return 0
        if args[0] == "status":
            versions = sorted(applied_versions(backend)) if _has_bookkeeping(backend) else []
            pending = [name for v, name, _ in MIGRATIONS if v not in versions]
            print(f"backend={backend.backend_type} applied={versions} pending={pending}")
            return 0
        print("usage: python -m histor.migrations [up|status]", file=sys.stderr)
        return 2
    finally:
        backend.close()


def _has_bookkeeping(backend: Backend) -> bool:
    with backend.read() as tx:
        if tx.backend_type == "sqlite":
            return tx.one("SELECT name FROM sqlite_master WHERE type='table' AND name='schema_migrations'") is not None
        return tx.one("SELECT tablename FROM pg_tables WHERE schemaname = current_schema() "
                      "AND tablename = 'schema_migrations'") is not None


if __name__ == "__main__":
    raise SystemExit(main())
